### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by Eliott-Guevel**
First version of the Molecule documentation, needs more abstract images, correct hyperlinks between tutorials as well as more details on certain parts

### CODE REVIEW

**Review by labordep — CHANGES_REQUESTED** [review]
There is a big problem in this PR, all Molecule files are here (and modified). 
What is it ?
Can you create a PR with only the documentation part ?

**Review by labordep — CHANGES_REQUESTED** [review]
This PR remove all the source code !
I cannot accept it :)
You need to resolve the problem that impact all the source code.

**Comment by labordep** [comment]
I have the explanation :  

```
I just wanted to let people who are using Pharo12 that they might notice some changes while exporting their code to github now.

We are introducing a TonelV3 format. The goals are to:
- Follow the spec that was agreed upon because currently we have symbols instead of strings in some places and that made it incompatible with Gemstone or Vast 
- Add missing informations. This is because in Pharo we have packages and tags but the only thing exported is the category. So reading the categories was ambiguous and relied on some heuristic. Loading the same class in two pharo image could load the class in different packages depending on the state of the image. 
- We want to add meta data for new features (not yet done). For example there is a new feature to rename a class and keep the old name as a deprecated alias for a while. We would like to be able to declare those info in the fluid class definition and in the Tonel format.

The new format still exports the category (but there is a setting to not export it) to stay backward compatible for now. 
Using the Tonel paser to read classes that were exported before Pharo 12 can have some difficulties to manage the tags, but the TonelReader class that is used by Iceberg knows how to resolve all of those problem to ensure the classes are in the right packages and in the right classes!
```

So don't use Pharo 12 for this work. Can you re send your modifications with P11 ? Thanks.

**Comment by Eliott-Guevel** [comment]
Wouldn't it be possible to merge this pull request instead of pulling it, so that the documentation part is added without necessitating to have the updated source code of Molecule in this particular pull request ?

**Pull request closed without merging**
